version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: gmongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER'
      - 'MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASS'
    volumes:
      - ${MONGODB_PATH}:/data/db

  redis:
    image: redis:6.2.6-alpine
    container_name: gredis
    restart: unless-stopped
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9.15-management-alpine
    container_name: grabbit
    restart: unless-stopped
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=$RABBITMQ_USER'
      - 'RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS'
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
