version: '3.1'

services:
  cassandra:
    image: cassandra:4
    container_name: gcassandra
    restart: unless-stopped
    ports:
      - 9042:9042
    volumes:
      - ${CASSANDRA_DATA}:/var/lib/cassandra

  redis:
    image: redis:6.2.6-alpine
    container_name: gredis
    restart: unless-stopped
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9.15-management-alpine
    container_name: grabbit
    restart: unless-stopped
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=$RABBITMQ_USER'
      - 'RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS'
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
