version: '3.1'

services:
  couchdb:
    image: couchdb:3.2
    container_name: gcouchdb
    restart: unless-stopped
    ports:
      - 5984:5984
    environment:
      - 'COUCHDB_USER=$COUCHDB_USER'
      - 'COUCHDB_PASSWORD=$COUCHDB_PASS'
    volumes:
      - ${COUCHDB_PATH}:/opt/couchdb/data

  redis:
    image: redis:6.2.6-alpine
    container_name: gredis
    restart: unless-stopped
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9.15-management-alpine
    container_name: grabbit
    restart: unless-stopped
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=$RABBITMQ_USER'
      - 'RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS'
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
