spring:
  application:
    name: galleries

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

logging:
  level:
    me.giobyte8.galleries.scanner: DEBUG

galleries:
  security:
    remember_me_key: ${GL_REMEMBER_ME_KEY:dev-unsafe-change-me}
  scanner:
    amqp:
      exchange_gl: GL_EXCHANGE
      queue_scan_requests: GL_SCAN_REQUESTS
      queue_gen_thumb_requests: GL_GEN_THUMB_REQUESTS
      queue_del_thumb_requests: GL_DEL_THUMB_REQUESTS
    content_dirs:
      root_path: ${SCANNER_CONTENT_DIR:/replace/in/intellij/spring/override}
    image_file_extensions:
      - jpeg
      - jpg
      - png
      - heic
      - webp
    video_file_extensions:
      - mp4
      - mov
      - m4v

neo4j:
  uri: neo4j://${NEO4J_HOST:localhost}:${NEO4J_PORT:7687}
  username: ${NEO4J_USERNAME:neo4j}
  password: ${NEO4J_PASSWORD:neo4j_devpass}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

  otlp:
    metrics:
      export:
        enabled: false
        url: http://localhost:4318/v1/metrics

        # Use higher value in production
        step: 5s
