version: '3.8'
name: galleries

services:
  sync-sch:
    image: giobyte8/gl-synchronizer:1.0.0
    container_name: gl-sync-sch
    user: $UID:$GID
    volumes:
      - "$CONTENT_DIR:/opt/galleries/content_dir"
      - "$RUNTIME_DIR:/opt/galleries/runtime_dir"
      - "$SYNCHRONIZER_CONFIG:/opt/galleries/config"
    env_file:
      - synchronizer.docker.env
    entrypoint: ["supercronic", "/opt/galleries/config/sync_scheduler.crontab"]

  synchronizer:
    image: giobyte8/gl-synchronizer:1.0.0
    container_name: gl-sync
    user: $UID:$GID
    volumes:
      - "$CONTENT_DIR:/opt/galleries/content_dir"
      - "$RUNTIME_DIR:/opt/galleries/runtime_dir"
    env_file:
      - synchronizer.docker.env

  http_downloader:
    image: giobyte8/gl-http_downloader:1.3.0
    container_name: gl-downloader
    user: $UID:$GID
    volumes:
      - "$CONTENT_DIR:/opt/galleries/content_dir"
      - "$RUNTIME_DIR:/opt/galleries/runtime_dir"
      - "$HTTP_DOWNLOADER_CONFIG:/opt/galleries/config"
    env_file:
      - http_downloader.docker.env
