spring:

  # Actual connection details are overridden during tests execution
  # to match test container settings, via '@ServiceConnection' annotation
  rabbitmq:
    host: localhost

logging:
  level:
    me.giobyte8.galleries.scanner: DEBUG

galleries:
  scanner:
    amqp:
      exchange_gl: GL_EXCHANGE
      queue_scan_requests: GL_SCAN_REQUESTS
      queue_gen_thumb_requests: GL_GEN_THUMB_REQUESTS
      queue_del_thumb_requests: GL_DEL_THUMB_REQUESTS

    content_dirs:
      root_path: src/test/resources/galleries
    image-file-extensions:
      - jpg
      - heic

neo4j:

  # uri is override during tests execution to match test container settings
  uri: neo4j://localhost:7687

  # Dedicated neo4j instance for integration tests doesn't require auth
  # We just enter dummy values to prevent client code to fail during
  # auth token generation
  username: none
  password: none
