
logging:
  level:
    me.giobyte8.galleries.scanner: DEBUG

galleries:
  scanner:
    amqp:
      exchange_gl: GL_EXCHANGE
      queue_scan_requests: GL_SCAN_REQUESTS
      queue_scan_hooks: GL_SCAN_HOOKS
      queue_scan_discovered_files: GL_SCAN_DISCOVERED_FILES
    content_dirs:
      root_path: src/test/resources/galleries
    media-files-extensions:
      - jpg

neo4j:
  uri: neo4j://localhost:7687
  username: neo4j
  password: neo4j_devpass
