spring:
  rabbitmq:
    username: dev
    password: devpass

logging:
  level:
    me.giobyte8.galleries.scanner: DEBUG

galleries:
  scanner:
    amqp:
      exchange_gl: GL_EXCHANGE
      queue_scan_requests: GL_SCAN_REQUESTS
      queue_scan_hooks: GL_SCAN_HOOKS
      queue_scan_discovered_files: GL_SCAN_DISCOVERED_FILES
    content_dirs:
      root_path: src/test/resources/galleries
    media-files-extensions:
      - jpg

neo4j:

  # Port has been updated from default to integration tests instance's
  uri: neo4j://localhost:7087

  # Dedicated neo4j instance for integration tests doesn't require auth
  # We just enter dummy values to prevent client code to fail during
  # auth token generation
  username: none
  password: none
