spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:gl}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: ${SCANNER_SPRING_JPA_SHOW_SQL:false}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

logging:
  level:
    me.giobyte8.galleries.scanner: DEBUG

galleries:
  scanner:
    amqp:
      exchange_gl: GL_EXCHANGE
      queue_scan_orders: GL_SCAN_ORDERS
      queue_scan_hooks: GL_SCAN_HOOKS
      queue_scan_discovered_files: GL_SCAN_DISCOVERED_FILES
    content_dirs:
      root_path: ${SCANNER_CONTENT_DIR:/replace/with/your/local/dev/galleries/path}
    media_files_extensions:
      - jpeg
      - jpg
      - png
      # - mp4
      # TODO add support for raw formats

neo4j:
  uri: neo4j://localhost:7687
  username: neo4j
  password: neo4j_devpass
